### ISSUE TITLE
Update Marathon version to 0.7.2

### ISSUE THREAD

**Issue by VictorIreri** [Malinskiy/homebrew-tap#4]
Looks like the following file needs updating to match the [latest Marathon release version](https://github.com/MarathonLabs/marathon/releases) (currently 0.7.2).
https://github.com/Malinskiy/homebrew-tap/blob/master/Formula/marathon.rb

**Comment by Malinskiy** [comment]
@VictorIreri thanks for the reminder, I forgot about this during the release. Need to automate this part in the future.
Will update the tap today

**Comment by Malinskiy** [comment]
Done
